name: Test

on:
  schedule:
    # '0 8 * * 1-5' translates to:
    # 0: Minute 0
    # 8: Hour 8 (08:00 UTC, which is 12:00 AM PST)
    # *: Every day of the month
    # *: Every month
    # 1-5: Monday through Friday
    - cron: '*/5 * * * *' 
  workflow_dispatch: 

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run Test
        run: echo "test"